Update install script

diff --git a/static/unchained/install b/static/unchained/install
--- a/static/unchained/install
+++ b/static/unchained/install
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+echo "   __  __           __          _                __"
+echo "  / / / /___  _____/ /_  ____ _(_)___  ___  ____/ /"
+echo " / / / / __ \\/ ___/ __ \\/ __ \`/ / __ \\/ _ \\/ __  /"
+echo "/ /_/ / / / / /__/ / / / /_/ / / / / /  __/ /_/ /  "
+echo "\____/_/ /_/\\___/_/ /_/\\__,_/_/_/ /_/\\___/\\__,_(_) "
+echo ""
+
 # List of required commands
 required_commands=("curl")
 
@@ -114,5 +121,9 @@ else
   # Non-Windows installation (Linux, macOS) proceeds as before
   chmod +x /tmp/$FILENAME
   sudo mv /tmp/$FILENAME $INSTALL_PATH/unchained
-  echo "Unchained $TAG has been installed to $INSTALL_PATH"
+  if [ $? -ne 0 ]; then
+    echo "Failed to install Unchained."
+  else
+    echo "Unchained $TAG has been installed to $INSTALL_PATH"
+  fi
 fi
